### ISSUE TITLE
Running dicom_archive_validation.py script on an inexistant upload ID make the script crash instead of returning appropriate error

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris-MRI#955]
```
$ run_dicom_archive_validation.py -p database_config_25.py -t /data/loris/data/tarchive/2023/DCM_2023-03-06_DICOM_DIR_2023-03-25_04h20m25s_4y8oen3t.tar -u 150

Traceback (most recent call last):
  File "/opt/loris/bin/mri/python/run_dicom_archive_validation.py", line 75, in <module>
    main()
  File "/opt/loris/bin/mri/python/run_dicom_archive_validation.py", line 71, in main
    DicomValidationPipeline(loris_getopt_obj, os.path.basename(__file__[:-3]))
  File "/opt/loris/bin/mri/python/lib/dcm2bids_imaging_pipeline_lib/dicom_validation_pipeline.py", line 29, in __init__
    super().__init__(loris_getopt_obj, script_name)
  File "/opt/loris/bin/mri/python/lib/dcm2bids_imaging_pipeline_lib/base_pipeline.py", line 89, in __init__
    self.load_imaging_upload_and_tarchive_dictionaries()
  File "/opt/loris/bin/mri/python/lib/dcm2bids_imaging_pipeline_lib/base_pipeline.py", line 162, in load_imaging_upload_and_tarchive_dictionaries
    if not success and not self.options_dict["force"]["value"]:
KeyError: 'force'
```

**Comment by cmadjar** [comment]
Fix will be released with 24.1.11 and pulled into main once released.
