### ISSUE TITLE
Push to S3 pipeline script - better handle options provided to the script

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris-MRI#959]
```
$ run_push_imaging_files_to_s3_pipeline.py -p database_config_25.py
Traceback (most recent call last):
  File "/opt/loris/bin/mri/python/run_push_imaging_files_to_s3_pipeline.py", line 65, in <module>
    main()
  File "/opt/loris/bin/mri/python/run_push_imaging_files_to_s3_pipeline.py", line 61, in main
    PushImagingFilesToS3Pipeline(loris_getopt_obj, os.path.basename(__file__[:-3]))
  File "/opt/loris/bin/mri/python/lib/dcm2bids_imaging_pipeline_lib/push_imaging_files_to_s3_pipeline.py", line 31, in __init__
    super().__init__(loris_getopt_obj, script_name)
  File "/opt/loris/bin/mri/python/lib/dcm2bids_imaging_pipeline_lib/base_pipeline.py", line 89, in __init__
    self.load_imaging_upload_and_tarchive_dictionaries()
  File "/opt/loris/bin/mri/python/lib/dcm2bids_imaging_pipeline_lib/base_pipeline.py", line 162, in load_imaging_upload_and_tarchive_dictionaries
    if not success and not self.options_dict["force"]["value"]:
KeyError: 'force'
```

Need to handle: 
- [x] wrong upload ID provided to the script
- [x] no upload ID provided to the script
- [x] remove option -t from the list of options in the description of the script

**Comment by cmadjar** [comment]
Fixed in 24.1-release branch and will be released with 24.1.11. Once 24.1.11 is released, will pull the changes into main so that those fixes are in 25
