### ISSUE TITLE
Better handle wrong configuration of S3 bucket in push to S3 script

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris-MRI#960]
```
$ run_push_imaging_files_to_s3_pipeline.py -p database_config_25_no_S3.py
Traceback (most recent call last):
  File "/opt/loris/bin/mri/python/run_push_imaging_files_to_s3_pipeline.py", line 65, in <module>
    main()
  File "/opt/loris/bin/mri/python/run_push_imaging_files_to_s3_pipeline.py", line 58, in main
    loris_getopt_obj = LorisGetOpt(usage, options_dict, os.path.basename(__file__[:-3]))
  File "/opt/loris/bin/mri/python/lib/lorisgetopt.py", line 109, in __init__
    aws_access_key_id=self.config_file.s3["aws_access_key_id"],
AttributeError: module 'database_config_25_no_S3' has no attribute 's3'
```

**Comment by cmadjar** [comment]
Fixed in 24.1-release and will go with next bug fix release 24.1.11. Once 24.1.11 is released, will merge tag in main for 25 release
